version: '3.9'

services:
  mongo_db:
    container_name: db_container
    image: mongo:4.4
    restart: always
    volumes:
      - mongo_data:/data/db

  api:
    container_name: app_container
    build: .
    ports:
      - 3009:3009
    environment:
      PORT: 3009
      MONGODB_URI: mongodb://mongo_db:27017
      DB_NAME: todoApp
    depends_on:
      - mongo_db

volumes:
  mongo_data: {}